abstract class SplashState {}
class InitialSplashState extends SplashState{}
class CartAppearSplashState extends SplashState{}
class CartPulseSplashState extends SplashState{}
class ProductsFlySplashState extends SplashState{}
class ShowTextSplashState extends SplashState{}
class CompletedSplashState extends SplashState{}
class NavigateToOnBoadingSplashState extends SplashState{}
class NavigateToLgonNiSplashState extends SplashState{}
class NavigateToHomeLayOutSplashState extends SplashState{}